#include <iostream>

/**
 * Problem #2:
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with  and , the first  terms will be:
 * 1,2,3,5,8,13,...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

 int main(){
    //Define limit from problem and starting constraints
    const int limit = 4'000'000;
    long long sum = 2;
    long long fib1 = 2;
    long long fib2 = 8;

    //Perform even fibonacci loop
    while (fib2 <= limit){

        sum += fib2;

        long long tmp = fib2;
        fib2 = fib2*4 + fib1;
        fib1 = tmp;
    }

    std::cout << "The sum of even Fibonacci numbers below 4 million is: " << sum << std::endl;

    return 0;
 }